### ISSUE TITLE
Has anyone used this?

### ISSUE THREAD

**Issue by bozeyman9000** [LeN0/mirrorscript#1]
So i just downloaded this, and im curious about running it, though i am relatively new to kali and linux, and i honestly dont feel like trying to figure out the exact order i should type various words with various spaces and such in the terminal. If someone has used this and has a good review about this i would love to read it.

**Comment by bozeyman9000** [comment]
just used it, i feel safer using the offcial repositories...

**Comment by IceM4nn** [comment]
The script is safe, it just change your official repo to a better mirrors which helps increase the `apt update` and similar operation to be much faster. The mirrors are official mirrors from Kali so nothing you should worry about. I've used the script before and things are good. I've an article about it [here](https://www.metahackers.pro/speed-kali-linux-update/). Thanks to @LeN0 for the script.

**Comment by jayantamadhav** [comment]
Just like @IceM4nn said in his blog, this script just changes the default mirror, its safe and also the first time you run this script , it creates a back-up of the original sources.list as sources.list.bak in the same folder so if things go wrong somewhere, you can revert back.
Cheers guys

P.S It uses official mirrors
